### PR TITLE
Add `R` binds to `helix.js`

### PR DESCRIPTION
**Pull request by SimonRask**

### CODE REVIEW

**Comment by DCsunset** [comment]
Hi, thanks for you contribution. However, I don't think it's necessary to add another option as you can run `modalEditor.delete` first and then `modalEditor.paste`

**Comment by SimonRask** [comment]
Yeah, that might be better. I don't have much experience with the vscode API, but my thought was that it would potentially be better to a single call to `TextEditor.edit()`. I would be glad to add the replace functionality for the helix keymap according your suggestion. Whatever you prefer :)

**Comment by DCsunset** [comment]
It might be slightly better in performance to have one call, but unless it's a significant improvement (with evidence provided), I think the complexity outweighs the benefit. I think you can go ahead with the `delete` command.

**Comment by SimonRask** [comment]
This should work :)

**Review by DCsunset — APPROVED** [review]

**Comment by DCsunset** [comment]
Merged into main branch with squashing

**Pull request closed without merging**
